name: Quant Bot V3

on:

  schedule:

    # 每天日本时间 21:00
    # UTC 12:00 = JST 21:00
    - cron: '0 12 * * *'

  workflow_dispatch:


jobs:

  run-bot:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Quant Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Commit CSV files
        run: |

          git config --global user.name "github-actions[bot]"

          git config --global user.email \
          "41898282+github-actions[bot]@users.noreply.github.com"

          git add history.csv invest_log.csv

          git diff --cached --quiet || \
          git commit -m "Auto update investment records"

          git push
